export const UFS: Array<{ sigla: string; nome: string; codigoIbge: number }> = [
  { sigla: "AC", nome: "Acre", codigoIbge: 12 },
  { sigla: "AL", nome: "Alagoas", codigoIbge: 27 },
  { sigla: "AP", nome: "Amapá", codigoIbge: 16 },
  { sigla: "AM", nome: "Amazonas", codigoIbge: 13 },
  { sigla: "BA", nome: "Bahia", codigoIbge: 29 },
  { sigla: "CE", nome: "Ceará", codigoIbge: 23 },
  { sigla: "DF", nome: "Distrito Federal", codigoIbge: 53 },
  { sigla: "ES", nome: "Espírito Santo", codigoIbge: 32 },
  { sigla: "GO", nome: "Goiás", codigoIbge: 52 },
  { sigla: "MA", nome: "Maranhão", codigoIbge: 21 },
  { sigla: "MT", nome: "Mato Grosso", codigoIbge: 51 },
  { sigla: "MS", nome: "Mato Grosso do Sul", codigoIbge: 50 },
  { sigla: "MG", nome: "Minas Gerais", codigoIbge: 31 },
  { sigla: "PA", nome: "Pará", codigoIbge: 15 },
  { sigla: "PB", nome: "Paraíba", codigoIbge: 25 },
  { sigla: "PR", nome: "Paraná", codigoIbge: 41 },
  { sigla: "PE", nome: "Pernambuco", codigoIbge: 26 },
  { sigla: "PI", nome: "Piauí", codigoIbge: 22 },
  { sigla: "RJ", nome: "Rio de Janeiro", codigoIbge: 33 },
  { sigla: "RN", nome: "Rio Grande do Norte", codigoIbge: 24 },
  { sigla: "RS", nome: "Rio Grande do Sul", codigoIbge: 43 },
  { sigla: "RO", nome: "Rondônia", codigoIbge: 11 },
  { sigla: "RR", nome: "Roraima", codigoIbge: 14 },
  { sigla: "SC", nome: "Santa Catarina", codigoIbge: 42 },
  { sigla: "SP", nome: "São Paulo", codigoIbge: 35 },
  { sigla: "SE", nome: "Sergipe", codigoIbge: 28 },
  { sigla: "TO", nome: "Tocantins", codigoIbge: 17 },
];
